apiVersion: 1

datasources:
  - name: Postgres
    uid: fraud_pg
    type: postgres
    access: proxy
    url: postgres:5432
    user: ${POSTGRES_USER}
    isDefault: true
    jsonData:
      database: ${POSTGRES_DB}
      sslmode: disable
      postgresVersion: 1600
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    editable: true
